In [26]:
import os
from pathlib import Path

import cv2
import imageio.v3 as iio
import numpy as np
import skimage as sk
from matplotlib import image
from PIL import Image

In [15]:
image_dir = Path("./data/micro_jump")
files = list(image_dir.glob("*.png"))

In [17]:
files

[PosixPath('data/micro_jump/screen_1751_3230851_0.png'),
 PosixPath('data/micro_jump/screen_1751_3230851_1.png'),
 PosixPath('data/micro_jump/screen_1751_3230851_2.png'),
 PosixPath('data/micro_jump/screen_1751_3230851_3.png'),
 PosixPath('data/micro_jump/screen_1751_3191231_1.png'),
 PosixPath('data/micro_jump/screen_1751_3230851_4.png')]

In [68]:
%%timeit
array = np.array([cv2.imread(str(f), cv2.IMREAD_GRAYSCALE) for f in files])

# array = np.zeros((len(files), 1080, 1080), dtype=np.uint8)
# for i, f in enumerate(files):
#     array[i] = cv2.imread(str(f), cv2.IMREAD_GRAYSCALE)

45.8 ms ± 340 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [66]:
array

array([[[ 5,  1,  1, ...,  0,  0,  0],
        [ 3,  2,  0, ...,  0,  0,  0],
        [ 0,  0,  3, ...,  0,  0,  0],
        ...,
        [ 0,  2,  1, ..., 15, 19, 23],
        [ 2,  1,  0, ...,  6,  9, 12],
        [ 1,  1,  0, ...,  3,  4,  7]],

       [[38, 22, 11, ...,  0,  0,  0],
        [31, 17, 10, ...,  0,  0,  0],
        [23, 15,  8, ...,  0,  0,  0],
        ...,
        [ 1,  1,  1, ..., 47, 44, 43],
        [ 1,  1,  1, ..., 45, 47, 43],
        [ 1,  0,  0, ..., 40, 46, 47]],

       [[49, 35, 19, ...,  0,  0,  0],
        [48, 29, 16, ...,  0,  0,  0],
        [39, 24, 11, ...,  0,  0,  0],
        ...,
        [ 1,  1,  1, ..., 61, 62, 56],
        [ 2,  1,  1, ..., 62, 66, 62],
        [ 2,  1,  0, ..., 59, 58, 61]],

       [[19, 19, 14, ...,  0,  0,  0],
        [22, 18, 13, ...,  0,  0,  0],
        [18, 15, 11, ...,  0,  0,  0],
        ...,
        [ 4,  4,  3, ..., 40, 37, 42],
        [ 3,  3,  2, ..., 38, 39, 36],
        [ 3,  2,  3, ..., 33, 36, 35]],

    

In [48]:
%%timeit
array = []
for f in files:
    img = Image.open(f)
    img_arr = np.array(img)
    array.append(img_arr)
array = np.stack(array)

52.6 ms ± 175 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [42]:
array[0]

array([[ 5,  1,  1, ...,  0,  0,  0],
       [ 3,  2,  0, ...,  0,  0,  0],
       [ 0,  0,  3, ...,  0,  0,  0],
       ...,
       [ 0,  2,  1, ..., 15, 19, 23],
       [ 2,  1,  0, ...,  6,  9, 12],
       [ 1,  1,  0, ...,  3,  4,  7]], dtype=uint8)

In [37]:
%%timeit
array = []
for f in files:
    img = iio.imread(f)
    array.append(img)

54.6 ms ± 1.26 ms per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [28]:
array[0]

array([[ 5,  1,  1, ...,  0,  0,  0],
       [ 3,  2,  0, ...,  0,  0,  0],
       [ 0,  0,  3, ...,  0,  0,  0],
       ...,
       [ 0,  2,  1, ..., 15, 19, 23],
       [ 2,  1,  0, ...,  6,  9, 12],
       [ 1,  1,  0, ...,  3,  4,  7]], dtype=uint8)

In [38]:
%%timeit
array = []
for f in files:
    img = sk.io.imread(f)
    # img_arr = np.asarray(img)
    array.append(img)

54.1 ms ± 245 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


In [32]:
array[0]

array([[ 5,  1,  1, ...,  0,  0,  0],
       [ 3,  2,  0, ...,  0,  0,  0],
       [ 0,  0,  3, ...,  0,  0,  0],
       ...,
       [ 0,  2,  1, ..., 15, 19, 23],
       [ 2,  1,  0, ...,  6,  9, 12],
       [ 1,  1,  0, ...,  3,  4,  7]], dtype=uint8)